language: ruby
node_js:
  - 'node'
rvm:
  - 2.2
env:
  - TRAVIS_NODE_VERSION="12"
install:
  - nvm install $TRAVIS_NODE_VERSION
  - npm install
before_script:
  - gem install awesome_bot
  - npm install --global awesome-lint
script:
  - awesome-lint
  - awesome_bot README.md --white-list $(paste -d, -s white_listed_sites.txt) --allow-ssl --allow-redirect
